package com.heartcare.agni.utils.constants

object NavControllerConstants {
    const val PATIENT = "patient"
    const val PATIENT_SAVED = "patient_saved"
    const val APPOINTMENT_SELECTED = "appointment_selected"
    const val ADD_TO_QUEUE = "added_to_queue"
    const val PATIENT_ARRIVED = "patient_arrived"
    const val RESCHEDULED = "rescheduled"
    const val SCHEDULED = "scheduled"
    const val IF_RESCHEDULING = "ifRescheduling"
    const val SELECTED_INDEX = "selectedIndex"
    const val PIN_SCREEN = "pin_screen_flag"
    const val PASSWORD_SCREEN = "password_screen_flag"
    const val PRIOR_DX_SAVED = "prior_dx_saved"
    const val LOGGED_IN = "loggedIn"
    const val PASSWORD = "password"
    const val PASSWORD_SAVED = "password_saved"
    const val EMAIL = "email"
    const val MEDICATION_SAVED = "medication_saved"
    const val FAMILY_HISTORY_SAVED = "family_history_saved"
    const val ALLERGIES_SAVED = "allergies_saved"
    const val RISK_FACTORS_SAVED = "risk_factors_saved"
    const val RISK_FACTOR = "risk_factor"
    const val TOBACCO_CESSATION_SAVED = "tobacco_cessation_saved"
    const val TOBACCO_CESSATION = "tobacco_cessation"
    const val DIAGNOSIS = "diagnosis"
    const val DIAGNOSIS_SAVED = "diagnosis_saved"
    const val INTERVENTIONS_SAVED = "interventions_saved"
    const val TEST_EXAMINATION_SAVED = "test_examination_saved"
    const val REFERRAL_SAVED = "referral_saved"
    const val REFERRAL = "referral"
    const val REFERRAL_FROM_CVD = "referral_from_CVD"
    const val CAMPAIGN_ID = "campaign_id"
    const val CAMPAIGN_APPOINTMENT_ID = "campaign_appointment_id"
}