package com.heartcare.agni.utils.constants

object NavControllerConstants {
    const val PATIENT = "patient"
    const val PATIENT_SAVED = "patient_saved"
    const val APPOINTMENT_SELECTED = "appointment_selected"
    const val ADD_TO_QUEUE = "added_to_queue"
    const val PATIENT_ARRIVED = "patient_arrived"
    const val RESCHEDULED = "rescheduled"
    const val SCHEDULED = "scheduled"
    const val IF_RESCHEDULING = "ifRescheduling"
    const val SELECTED_INDEX = "selectedIndex"
    const val OTC_DISPENSED = "otc_dispensed"
    const val VACCINE_ERROR_TYPE = "vaccine_error_type"
    const val VACCINE = "vaccine_error_type"
    const val VACCINE_ADDED = "vaccine_added"
    const val PIN_SCREEN = "pin_screen_flag"
    const val PASSWORD_SCREEN = "password_screen_flag"
    const val PRIOR_DX_SAVED = "prior_dx_saved"
    const val LOGGED_IN = "loggedIn"
    const val PASSWORD = "password"
    const val PASSWORD_SAVED = "password_saved"
    const val EMAIL = "email"
    const val MEDICATION_SAVED = "medication_saved"
    const val FAMILY_HISTORY_SAVED = "family_history_saved"
    const val ALLERGIES_SAVED = "allergies_saved"
    const val RISK_FACTORS_SAVED = "risk_factors_saved"
    const val RISK_FACTOR = "risk_factor"
}